### ISSUE TITLE
CC3200 : error 32 (server not available)

### ISSUE THREAD

**Issue by fredsilvi** [xively/xively-client-c#141]
Hi,
I am evaluating xively client on CC3200, and I don't get any success : I systematically get a "connection to broker.xively.com:8883 has failed reason 32" error message.
xively_error.h ->    XI_MQTT_SERVER_UNAVAILIBLE,            /* 32 */

I suspect a TLS issue.
My configuration is based on :   
- service pack 1.0.1.11-2.9.0.0 (March 2017)
- SDK 1.3

Has CC3200 client been tested with this configuration ? (especially last service pack available)

Thanks in advance,
Frederic

Host Driver Version: 1.0.1.11
Build Version 2.9.0.0.31.1.4.0.1.1.0.3.37
Device is configured in default state 
Device started as STATION 
[WLAN EVENT] STA Connected to the AP: iPhone de Frederic , BSSID: 3a:34:51:5d:18:f1
[NETAPP EVENT] IP Acquired: IP=172.20.10.2 ,Gateway=172.20.10.1
SNTP_G: 1504167349, pool.ntp.org->0x8CC8CA95
SNTP_L: 1504167350, UT 3
close the user file: /cert/xively_cert_globalsign_rootca.der
connection to broker.xively.com:8883 has failed reason 32
[SOCK ERROR] - close socket (81) operation failed to transmit all queued packets

close the user file: /cert/xively_cert_globalsign_rootca.der
connection to broker.xively.com:8883 has failed reason 32
[SOCK ERROR] - close socket (82) operation failed to transmit all queued packets

close the user file: /cert/xively_cert_globalsign_rootca.der
connection to broker.xively.com:8883 has failed reason 32
[SOCK ERROR] - close socket (83) operation failed to transmit all queued packets

close the user file: /cert/xively_cert_globalsign_rootca.der
connection to broker.xively.com:8883 has failed reason 32
[SOCK ERROR] - close socket (84) operation failed to transmit all queued packets

**Comment by fredsilvi** [comment]
This issue was not a real one : it was due to credentials misuse. I have been fooled by the XI_MQTT_SERVER_UNAVAILIBLE error message...

**Comment by DellaBitta** [comment]
Sorry for the late reply. 

I was about to write that I was able to validate the CC3200 v1.3 SDK with that specific service pack, but it looks like you closed the issue before I could get a chance to reply!

I'm glad that everything has worked out. Let us know if you have any other problems.
