### ISSUE TITLE
Building examples fails in OS X High Sierra

### ISSUE THREAD

**Issue by mwieckowski** [xively/xively-client-c#176]
Ran Make at top level without any issue.  Changed into examples directory.  Ran Make.

[cc] /Users/username/Development/xively-client-c-master/examples/mqtt_logic_example/bin/mqtt_logic_example
ld: warning: directory not found for option '-L/Users/username/Development/xively-client-c-master/examples/mqtt_logic_example/../.././src/import/tls/wolfssl/src/.libs/'
Undefined symbols for architecture x86_64:
  "_wolfSSL_UseOCSPStapling", referenced from:
      _xi_bsp_tls_init in libxively.a(xi_bsp_tls_wolfssl.o)
  "_wolfSSL_UseSNI", referenced from:
      _xi_bsp_tls_init in libxively.a(xi_bsp_tls_wolfssl.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [/Users/username/Development/xively-client-c-master/examples/mqtt_logic_example/bin/mqtt_logic_example] Error 1
make: *** [mqtt_logic_example] Error 2

**Comment by atigyi** [comment]
Hi,

so these above are two linker errors: the linker cannot find two wolfssl functions: UseOCSPStapling and UseSNI. Only these are not found although many other wolfssl functions are used by xi_bsp_tls_wolfssl.c.
So based on available info, my assumption is you gave a path to the example build system where a custom built wolfssl static lib exists. But this custom built wolfssl lib does not have the two functions above. I've checked the wolfssl's ssl.c file, these function definitions are macro guarded by: HAVE_CERTIFICATE_STATUS_REQUEST and HAVE_SNI respectively.
To include these functions to your custom built wolfssl lib add: `--enable-sni` and `--enable-ocspstapling` to the configure script of wolfssl before the make.
As an example check files in xively-client-c repo: download_and_compile_wolfssl.sh and wolfssl.conf in directory: src/import/tls.

Hope this helps.

**Comment by atigyi** [comment]
If not the custom built wolfssl static lib is the case, could you please share what command you used building the the xively-client-c at top level and what command in the examples directory. Additionally did you change anything in any of the xively-client-c's makefiles. They have extension: .mk.

**Comment by mwieckowski** [comment]
Thanks so much!  That solved it.  I downloaded WolfSSL 3.13.0 and ran ./configure.  Both SNI and OCSP stapling were disabled by default.  I added the --enable-sni and --enable-ocspstapling options and rebuilt WolfSSL.  Then the Xively examples compiled and linked without any issue.

**Comment by atigyi** [comment]
👍

**Comment by mwieckowski** [comment]
@atigyi - while I have you, I am now getting a "connection has failed reason 32" response when I try to run any of the examples.  Where can I learn about this error code?  Looking at the src code, the error reason actually looks to be the state of the connection.  Any ideas?  In parallel, I ran "make tests" just to see if something obvious failed, and I am getting failure of:
xi_utest_rng.c:31: assert(r1 != r2): 0 vs 0
[. FAILED  ] utest_rng - xi_utest_rand (0 ms)

Maybe unrelated to the connection issue?

**Comment by atigyi** [comment]
The error 32 and the failing unit test might be caused by the same problem: your wolfssl build might not provide good enough random number. The unit test uses 
```
wc_InitRng
wc_RNG_GenerateBlock
wc_FreeRng
```
functions in `xi_bsp_rng_posix.c` (the last section).
Wolfssl does provide 4 versions of these functions. You should check which is enabled by your configuration and fix it to provide proper random number.

You may check our wolfssl build version in: `src/import/tls` directory, files: `download_and_compile_wolfssl.sh` and `wolfssl.conf`.

**Comment by atigyi** [comment]
OR you use our version of wolfssl static lib, currently we use v3.10.2-stable, as you can see in the file `download_and_compile_wolfssl.sh`.

If you type `make` at top level it should ask you to accept wolfssl lincenses, then it downloads and builds wolfssl with proper flags. And with this the xi_utest_rand should pass, and maybe even error 32 will go by. If my assumption stands.
So I would fix first the unit test, then if the error 32 still exists come back here.
Also do you have Xively credentials: account id, device id, password?

**Comment by mwieckowski** [comment]
@atigyi - I was able to fix the unit test.  Per you suggestion, I switched over to the Xively recommended WolfSSL release.  I also had to change the wolfssl.conf file to remove a trailing --enable-debug.  However, even though the unit tests now pass, I still get the error 32 issue.  I do have a xively account, a group with 1 device associated, and a channel to subscribe to.

**Comment by atigyi** [comment]
Hi, error 32 is thrown by the broker.xively.com, so probably your client already has a TLS connected socket. MQTT CONNECT is sent, but CONNACK has bad news for your client.
I can confirm the gibberish example above gives the 32 at me too.

My only bet here is you accidentally mixed up something in the credentials. I've created a temporary client on my account for you, please try this commandline with the `mqtt_logic_producer` example:

`./mqtt_logic_producer -a 4d3c7986-8d53-4cf8-903e-7fd30ff63be1 -u a01f4b4a-0b2a-49b5-a169-4e9261c164ce -P iDy94cu6pqL5R7Nn0B+U7jBnKdWaaObYZn8PGAyNPSY= -p Temperature`

also note the help message of an example:
```
./mqtt_logic_producer
Xively C Client Version: 1.3.2

-a --account-id is required
-u --username is required
-P --password is required
-p --publishtopic is required
```

Hope this'll help!

**Comment by mwieckowski** [comment]
Your example worked perfectly.  After digging into the docs a bit, I found the missing piece:  
```
The device authenticates by sending its Device ID as the MQTT Client ID, and its Device Secret as the MQTT Password. The MQTT Username can either be empty or the Device ID.
```
We were using the userId of the end user instead of the Device ID.
