### ISSUE TITLE
Code or old instructions issue?

### ISSUE THREAD

**Issue by ranshe** [xively/xively-client-c#80]
Build fails on Windows for me:
c:\ti\xively-client-c-master>gmake PRESET=CC3200_TLS_SOCKET clean

# Using build PRESET: "CC3200_TLS_SOCKET" to set CONFIG and TARGET variables:
.    XI_BSP_PLATFORM: [cc3200]
.    XI_BSP_TLS:      []
rm -f -rf \
        c:/ti/xively-client-c-master/bin/cc3200 \
        c:/ti/xively-client-c-master/obj/cc3200 \
        c:/ti/xively-client-c-master/obj/cc3200/tests \
        c:/ti/xively-client-c-master/obj/cc3200/libxively

c:\ti\xively-client-c-master>gmake PRESET=CC3200_TLS_SOCKET

# Using build PRESET: "CC3200_TLS_SOCKET" to set CONFIG and TARGET variables:
.    XI_BSP_PLATFORM: [cc3200]
.    XI_BSP_TLS:      []

# Xively C Client

. run 'make help' for more information, including a list of valid Build PRESETS.
.    CONFIG:          [bsp_cc3200-memory_fs-tls_socket]
.    TARGET:          [cc3200-static-release]
.    COMPILER:        [C:/ti/ccsv7/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/bin/armcl]

[C:/ti/ccsv7/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/bin/armcl] c:/ti/xively-client-c-master/obj/cc3200/libxively/io/fs/memory/xi_fs_memory.o
process_begin: CreateProcess(NULL, C:/ti/ccsv7/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/bin/armcl -DXI_DEBUG_OUTPUT=0 -DXI_DEBUG_ASSERT=0 -DXI_DEBUG_EXTRA_INFO=0 -DXI_
FS_MEMORY -DXI_PLATFORM_BASE_DUMMY -DXI_NO_TLS_LAYER -DXI_BSP_IO_NET_TLS_SOCKET -DXI_BSP -DXI_CROSS_TARGET -DXI_EMBEDDED_TESTS -DNO_WRITEV -fstrict-aliasing -IC:/ti/ccsv7
/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/include -mv7M4 -me -ms --define=css --define=cc3200 --define=WOLFSSL_NOOS_XIVELY --display_error_number --diag_warning=225 --
diag_wrap=off --abi=eabi --opt_for_speed=0 --code_state=16 --float_support=vfplib --preproc_with_compile --preproc_dependency=c:/ti/xively-client-c-master/obj/cc3200/libx
ively/io/fs/memory/xi_fs_memory.d --obj_directory=c:/ti/xively-client-c-master/obj/cc3200/libxively/io/fs/memory/ --asm_directory=c:/ti/xively-client-c-master/obj/cc3200/
libxively/io/fs/memory/ --output_file=c:/ti/xively-client-c-master/obj/cc3200/libxively/io/fs/memory/xi_fs_memory.o -O4 -IC:/ti/tirex-content/CC3200SDK_1.1.0/cc3200-sdk//
driverlib -IC:/ti/tirex-content/CC3200SDK_1.1.0/cc3200-sdk//inc -IC:/ti/tirex-content/CC3200SDK_1.1.0/cc3200-sdk//example/common -IC:/ti/tirex-content/CC3200SDK_1.1.0/cc3
200-sdk//simplelink/include -IC:/ti/tirex-content/CC3200SDK_1.1.0/cc3200-sdk//simplelink_extlib/provisioninglib -I. -Ic:/ti/xively-client-c-master/include/bsp -Ic:/ti/xiv
ely-client-c-master/src/libxively/platform/xi_thread -Ic:/ti/xively-client-c-master/include -Ic:/ti/xively-client-c-master/include_senml -Ic:/ti/xively-client-c-master/sr
c/libxively -Ic:/ti/xively-client-c-master/src/libxively/io/fs/memory -Ic:/ti/xively-client-c-master/src/bsp/platform/cc3200 -Ic:/ti/xively-client-c-master/src/libxively/
io/net -Ic:/ti/xively-client-c-master/src/libxively/memory -Ic:/ti/xively-client-c-master/src/libxively/event_loop -Ic:/ti/xively-client-c-master/src/libxively/time -Ic:/
ti/xively-client-c-master/src/libxively -Ic:/ti/xively-client-c-master/src/libxively/io -Ic:/ti/xively-client-c-master/src/libxively/io/fs -Ic:/ti/xively-client-c-master/
src/libxively/event_dispatcher -Ic:/ti/xively-client-c-master/src/libxively/datastructures -Ic:/ti/xively-client-c-master/src/libxively/mqtt/codec -Ic:/ti/xively-client-c
-master/src/libxively/mqtt/logic -Ic:/ti/xively-client-c-master/src/libxively/control_topic -Ic:/ti/xively-client-c-master/src/libxively/platform/dummy -Ic:/ti/xively-cli
ent-c-master/src/libxively/platform/dummy/xi_thread -Ic:/ti/xively-client-c-master/src/import/cmocka/include/ -Ic:/ti/xively-client-c-master/src/tests -Ic:/ti/xively-clie
nt-c-master/src/tests/tools -Ic:/ti/xively-client-c-master/src/tests/itests -Ic:/ti/xively-client-c-master/src/tests/itests/tools -Ic:/ti/xively-client-c-master/src/tests
/itests/tools/dummy -Ic:/ti/xively-client-c-master/src/libxively -Ic:/ti/xively-client-c-master/src/tests/itests/platform/dummy/xi_thread -c c:/ti/xively-client-c-master/
src/libxively/io/fs/memory/xi_fs_memory.c -o c:/ti/xively-client-c-master/obj/cc3200/libxively/io/fs/memory/xi_fs_memory.o, ...) failed.
make (e=2): The system cannot find the file specified.
Makefile:124: recipe for target 'c:/ti/xively-client-c-master/obj/cc3200/libxively/io/fs/memory/xi_fs_memory.o' failed
gmake: *** [c:/ti/xively-client-c-master/obj/cc3200/libxively/io/fs/memory/xi_fs_memory.o] Error 2

**Comment by olgierdh** [comment]
Hi Ranshe,

Thank you for sharing your issue and for trying our library. 

From what I can see It seems that you didn’t add the “bin" and the “cygwin" paths to the PATH variable. Adding these paths to PATH is described in [Step 4 of 7: Build the Xively C Client library](https://developer.xively.com/docs/ti-cc3200#section-step-4-of-7-build-the-xively-c-client-library). In order to do this you have to type in your console:

```
PATH=%PATH%;c:\ti\ccsv6\utils\bin
PATH=%PATH%;c:\ti\ccsv6\utils\cygwin
```

This way Windows should be able to create directories correctly and compile the xively-client-c properly. 

Please let us know if it helped and if you have other issues. 

Best regards,
Olgierd Humeńczuk

**Comment by ranshe** [comment]
If I hadn't, gmake would have have been reported as non existent code/command - but you can see that it's running for "clean" target.

**Comment by olgierdh** [comment]
Thanks for pointing that out. So you are using gcc-arm-none-eabi compiler. Our Makefile for CC3200 is crafted for TI ARM Compiler. Would you mind trying the latter one instead ?

**Comment by ranshe** [comment]
Thanks, that worked!

**Comment by olgierdh** [comment]
Great! Glad that help. Let us know if you have any other issues.
